import os
import sys
from dotenv import load_dotenv

# Ensure the backend directory is in the sys.path so app imports resolve
scripts_dir = os.path.dirname(os.path.abspath(__file__))
backend_dir = os.path.dirname(scripts_dir)
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

# Load environment variables from backend/.env
env_path = os.path.join(backend_dir, ".env")
load_dotenv(env_path)

def main():
    default_url = "https://github.com/langchain-ai/langchain"
    repo_url = sys.argv[1] if len(sys.argv) > 1 else default_url
    
    print(f"Verifying Contribution PDF Generation for: {repo_url}")
    
    try:
        from app.utils.github_parser import parse_github_url
        from app.services.repo_service import RepoService
        from app.pdf.templates.contribution_report import ContributionReportTemplate
        
        parsed = parse_github_url(repo_url)
        owner = parsed["owner"]
        repo_name = parsed["repo"]
        
        print("Running repository analysis pipeline...")
        repo_service = RepoService()
        analysis_result = repo_service.analyze_repository(repo_url, mode="FAST_MVP")
        
        roadmap = analysis_result.get("roadmap", {})
        if not roadmap:
            print("[INFO] No contributor roadmap generated by default. Injecting a mock issue to verify PDF generation pipeline...")
            mock_raw_issue = {
                "number": 9999,
                "title": "Mock Issue: Add support for custom JSON encoders in response formatting",
                "body": "When returning JSON responses, we should support passing a custom JSONEncoder subclass to serialize complex types. Right now, it defaults to the standard json.JSONEncoder which fails on objects like datetime.",
                "labels": ["good first issue", "python"],
                "owner": owner,
                "repo": repo_name,
                "html_url": f"https://github.com/{owner}/{repo_name}/issues/9999"
            }
            
            from app.services.issue_guidance_service import IssueGuidanceService
            guidance_service = IssueGuidanceService()
            
            mock_comments = [
                {"author": "maintainer1", "body": "This sounds like a great enhancement. We should make sure we support it in the Flask response class."},
                {"author": "user1", "body": "+1, I need this for datetime serialization."}
            ]
            
            guidance = guidance_service.generate_guidance({
                "issue": mock_raw_issue,
                "repo_summary": analysis_result.get("summary", {}),
                "repository_map": analysis_result.get("repository_map", {}),
                "comments": mock_comments,
                "all_files": analysis_result.get("all_files", []),
                "all_dirs": analysis_result.get("all_dirs", [])
            })
            
            issue_entry = {
                "raw_issue": mock_raw_issue,
                "analysis": guidance.get("analysis", {}),
                "exploration_hints": guidance.get("exploration_hints", {})
            }
            analysis_result["issues"] = [issue_entry]
            
            roadmap = {
                "best_issue_to_start": {
                    "issue_number": 9999,
                    "title": mock_raw_issue["title"],
                    "difficulty_level": "Beginner"
                },
                "prerequisites": ["Understand standard python JSON serialization"],
                "step_by_step_tasks": ["Identify response class location", "Update json serialization call", "Add unit tests"]
            }
            analysis_result["roadmap"] = roadmap

        best_issue = roadmap.get("best_issue_to_start", {})
        best_issue_number = best_issue.get("issue_number", "Unknown")
        best_issue_title = best_issue.get("title", "Recommended Issue")
        
        # Find matching issue to extract difficulty
        difficulty = "Beginner"
        for issue_entry in analysis_result.get("issues", []):
            raw = issue_entry.get("raw_issue", {})
            if raw.get("number") == best_issue_number:
                difficulty = issue_entry.get("analysis", {}).get("difficulty", "Beginner")
                break
                
        learning_time = analysis_result.get("summary", {}).get("estimated_learning_time", "Unknown")
        
        print("Generating Contribution PDF document...")
        pdf_bytes = ContributionReportTemplate.generate(
            repo_name=repo_name,
            analysis_data=analysis_result
        )
        
        generated_dir = os.path.join(backend_dir, "generated")
        os.makedirs(generated_dir, exist_ok=True)
        
        pdf_filename = f"{repo_name.lower()}_contribution_guide.pdf"
        pdf_path = os.path.join(generated_dir, pdf_filename)
        
        with open(pdf_path, "wb") as f:
            f.write(pdf_bytes)
            
        print("\n-------------------------------------------------")
        print(f"Repository: {repo_name}")
        print(f"Recommended Issue: #{best_issue_number} - {best_issue_title}")
        print(f"Difficulty: {difficulty}")
        print(f"Learning Time: {learning_time}")
        print(f"Output path: backend/generated/{pdf_filename}")
        print("Status: SUCCESS")
        print("-------------------------------------------------")
        
        sys.exit(0)

    except Exception as e:
        import traceback
        print("\n-------------------------------------------------")
        print("Status:\nFAILURE")
        print(f"Error: {e}")
        print("-------------------------------------------------")
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
