from io import BytesIO
from reportlab.platypus import SimpleDocTemplate
from app.pdf.styles import PAGE_MARGIN
from app.pdf.components import NumberedCanvas

class PDFService:
    """
    Centralized service responsible for:
    - Initializing PDF documents
    - Applying shared styles
    - Registering page templates
    - Returning generated PDF bytes
    
    This service is decoupled from specific repository or guide logic.
    """
    @staticmethod
    def generate_pdf(flowables: list, has_cover: bool = True, title: str = "RepoGuideAI Report") -> bytes:
        """
        Takes a list of ReportLab Flowables, wraps them in a SimpleDocTemplate
        configured with standard margins, runs the NumberedCanvas two-pass builder
        to calculate total pages and draw headers/footers, and returns the generated PDF bytes.
        """
        buffer = BytesIO()
        
        # Initialize document template with standard 0.75-inch (54pt) margins
        doc = SimpleDocTemplate(
            buffer,
            rightMargin=PAGE_MARGIN,
            leftMargin=PAGE_MARGIN,
            topMargin=PAGE_MARGIN,
            bottomMargin=PAGE_MARGIN
        )
        
        # Configure custom attributes on document object for NumberedCanvas to read dynamically
        doc.has_cover_page = has_cover
        doc.pdf_title = title
        
        # Build the document flowables into PDF
        doc.build(flowables, canvasmaker=NumberedCanvas)
        
        # Fetch the generated bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
