from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator


class RepositoryMap(BaseModel):
    """Categorized directory structure of the repository."""
    frontend: List[str] = Field(default_factory=list)
    backend: List[str] = Field(default_factory=list)
    tests: List[str] = Field(default_factory=list)
    docs: List[str] = Field(default_factory=list)
    config: List[str] = Field(default_factory=list)
    scripts: List[str] = Field(default_factory=list)
    other: List[str] = Field(default_factory=list)

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "frontend": ["src/components", "src/styles"],
                "backend": ["api", "models"],
                "tests": ["tests/unit", "tests/integration"],
                "docs": ["docs", "wiki"],
                "config": [".github/workflows"],
                "scripts": ["scripts"],
                "other": ["assets"]
            }
        }
    )


class IssueComment(BaseModel):
    """A single structured comment on a GitHub issue."""
    author: str = Field(..., description="Author of the comment")
    body: str = Field(..., description="Body text of the comment")
    created_at: Optional[str] = Field(None, description="ISO timestamp of comment creation")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "author": "octocat",
                "body": "This issue might be related to the API validation logic.",
                "created_at": "2023-10-01T12:00:00Z"
            }
        }
    )


class IssueAnalysis(BaseModel):
    """LLM analysis providing a beginner-friendly explanation of an issue."""
    difficulty: str = Field(..., pattern=r"^(Beginner|Intermediate|Advanced)$")
    skills_required: List[str] = Field(default_factory=list)
    affected_area: str = Field(..., min_length=1)
    beginner_explanation: str = Field(..., min_length=1)
    confidence_score: int = Field(..., ge=0, le=100)

    @field_validator("skills_required")
    @classmethod
    def validate_lists(cls, value: List[str]) -> List[str]:
        return [item.strip() for item in value if isinstance(item, str) and item.strip()]

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "difficulty": "Beginner",
                "skills_required": ["Python", "FastAPI"],
                "affected_area": "app/api/endpoints",
                "beginner_explanation": "This issue asks to add a new validation check to the login endpoint.",
                "confidence_score": 90
            }
        }
    )


class ExplorationHints(BaseModel):
    """LLM hints guiding a beginner on where to explore in the codebase."""
    affected_area: str = Field(..., min_length=1)
    likely_directories: List[str] = Field(default_factory=list)
    possible_files: List[str] = Field(default_factory=list)
    reasoning: str = Field(..., min_length=1)
    confidence: int = Field(..., ge=0, le=100)

    @field_validator("likely_directories", "possible_files")
    @classmethod
    def validate_lists(cls, value: List[str]) -> List[str]:
        return [item.strip() for item in value if isinstance(item, str) and item.strip()]

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "affected_area": "Authentication routes",
                "likely_directories": ["app/api", "app/services"],
                "possible_files": ["app/api/auth.py", "app/services/auth_service.py"],
                "reasoning": "The issue involves validation during login, which typically happens in the auth routes.",
                "confidence": 85
            }
        }
    )


class AnalyzedIssue(BaseModel):
    """Wrapper for a GitHub issue including AI analysis and exploration hints."""
    raw_issue: Dict[str, Any] = Field(..., description="Raw issue data from GitHub API")
    # Optional because we degrade gracefully if the LLM generation fails
    analysis: Optional[IssueAnalysis] = Field(None, description="Beginner-friendly explanation")
    exploration_hints: Optional[ExplorationHints] = Field(None, description="Hints on where to look in the repo")


class RepositoryAnalysisResponse(BaseModel):
    """Final aggregated response for a repository analysis request."""
    metadata: Dict[str, Any] = Field(..., description="Basic repository metadata")
    summary: Dict[str, Any] = Field(..., description="Repository summary generated by LLM")
    repository_map: RepositoryMap = Field(..., description="Categorized repository directories")
    issues: List[AnalyzedIssue] = Field(default_factory=list, description="Top issues with analysis and hints")
    roadmap: Dict[str, Any] = Field(..., description="Contribution roadmap generated by LLM")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "metadata": {"name": "repo-guide-ai", "stars": 100},
                "summary": {"repository_purpose": "AI assistant for open source contributions"},
                "repository_map": {
                    "frontend": ["frontend/src"],
                    "backend": ["backend/app"],
                    "tests": [],
                    "docs": [],
                    "config": [],
                    "scripts": [],
                    "other": []
                },
                "issues": [],
                "roadmap": {"best_issue_to_start": {"issue_number": 1, "title": "Fix login page"}}
            }
        }
    )