from app.pdf.pdf_service import PDFService
from app.pdf.components import (
    create_cover_page,
    create_section_title,
    create_info_box,
    create_table,
    create_bullet_list,
    create_checklist,
    create_horizontal_divider
)
from reportlab.platypus import Paragraph, Spacer
from app.pdf.styles import get_shared_styles, SPACING_XS, SPACING_SM, SPACING_MD, SPACING_LG
import datetime

class RepositoryReportTemplate:
    """
    Report template for the Repository Guide.
    Composes shared visual components using real backend repository analysis data.
    """
    @staticmethod
    def generate(repo_name: str, analysis_data: dict = None, author: str = "RepoGuideAI", date_str: str = None) -> bytes:
        styles = get_shared_styles()
        flowables = []
        
        # Fall back to empty dictionary if no analysis data is provided
        if not analysis_data:
            analysis_data = {}
            
        metadata = analysis_data.get("metadata", {})
        summary = analysis_data.get("summary", {})
        repo_map = analysis_data.get("repository_map", {})
        
        # Extract metadata fields
        owner = metadata.get("owner", "Unknown Owner")
        name = metadata.get("name", repo_name)
        description = metadata.get("description", "No description available.")
        
        # Extract summary fields
        purpose = summary.get("repository_purpose", "No core purpose description provided.")
        beginner_summary = summary.get("beginner_friendly_summary", "No beginner summary provided.")
        difficulty = summary.get("difficulty_level", "Unknown")
        learning_time = summary.get("estimated_learning_time", "Unknown")
        target_users = summary.get("target_users", "Unknown")
        tech_stack = summary.get("tech_stack", [])
        first_steps = summary.get("first_steps", [])
        
        # 1. Cover Page
        cover_metadata = {
            "Repository": name,
            "Owner": owner,
            "Date": date_str or datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "Author": author,
            "Generated By": "RepoGuideAI Engine"
        }
        flowables.extend(create_cover_page(
            title="RepoGuideAI",
            subtitle=f"Repository Guide: {name}",
            metadata=cover_metadata
        ))
        
        # 2. Repository Overview
        flowables.append(create_section_title("1. Repository Overview"))
        flowables.append(Spacer(1, SPACING_SM))
        
        # Description callout or introduction
        flowables.append(Paragraph(f"<b>Description:</b> {description}", styles['DocBody']))
        flowables.append(Spacer(1, SPACING_XS))
        
        # Core Purpose
        flowables.append(Paragraph(f"<b>Core Purpose:</b> {purpose}", styles['DocBody']))
        flowables.append(Spacer(1, SPACING_XS))
        
        # Beginner Friendly Summary
        flowables.append(Paragraph(f"<b>Beginner Summary:</b> {beginner_summary}", styles['DocBody']))
        flowables.append(Spacer(1, SPACING_SM))
        
        # Facts Table
        facts_headers = ["Key Metric", "Details"]
        facts_rows = [
            ["Difficulty Level", difficulty],
            ["Estimated Learning Time", learning_time],
            ["Target Audience", target_users]
        ]
        flowables.append(create_table(facts_headers, facts_rows, col_widths=[150, None]))
        flowables.append(Spacer(1, SPACING_MD))
        
        # 3. Technology Stack
        flowables.append(create_section_title("2. Technology Stack"))
        flowables.append(Spacer(1, SPACING_SM))
        if tech_stack:
            # Render technologies using the bullet list component
            flowables.extend(create_bullet_list(tech_stack))
        else:
            flowables.append(Paragraph("No technology stack information available.", styles['DocBody']))
        flowables.append(Spacer(1, SPACING_MD))
        
        # 4. Recommended First Steps
        flowables.append(create_section_title("3. Recommended First Steps"))
        flowables.append(Spacer(1, SPACING_SM))
        if first_steps:
            for idx, step in enumerate(first_steps):
                flowables.append(Paragraph(f"<b>{idx + 1}.</b> {step}", styles['DocBody']))
                flowables.append(Spacer(1, SPACING_XS))
        else:
            flowables.append(Paragraph("No recommended first steps available.", styles['DocBody']))
        flowables.append(Spacer(1, SPACING_MD))
        
        # 5. Repository Map
        flowables.append(create_section_title("4. Repository Structure Map"))
        flowables.append(Spacer(1, SPACING_SM))
        
        map_headers = ["Category", "Key Directories & Files"]
        map_rows = []
        
        # Support both pydantic models (with __dict__) and plain dictionaries
        map_dict = repo_map if isinstance(repo_map, dict) else (getattr(repo_map, '__dict__', {}) or {})
        
        # Sort and filter non-empty categories
        categories = ["backend", "frontend", "tests", "docs", "config", "scripts", "other"]
        for cat in categories:
            items = map_dict.get(cat, [])
            if items:
                items_str = ", ".join(items)
                map_rows.append([cat.capitalize(), items_str])
                
        if map_rows:
            flowables.append(create_table(map_headers, map_rows, col_widths=[100, None]))
        else:
            flowables.append(Paragraph("No directory structure information available.", styles['DocBody']))
            
        # Build document and return generated PDF bytes
        # Specifying doc.pdf_title as f"Repository Guide - {name}" will be drawn on headers on later pages
        return PDFService.generate_pdf(flowables, has_cover=True, title=f"Repository Guide - {name}")
